idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "network_watchdog.c"
        "web_server.c"
        "buttons.c"
        "esp_now_receiver.c"
        "gps_parser.c"
        "metar_fetcher.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        esp_http_client
        json
        spiffs
        fatfs
        driver)
