name: Build Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Vostochnaya Baza (ESP32-S3)
      run: |
        . $IDF_PATH/export.sh
        cd vostochnaya_baza_s3
        idf.py set-target esp32s3
        idf.py build

    - name: Build Vostochnaya Udochka (ESP32-C3)
      run: |
        . $IDF_PATH/export.sh
        cd vostochnaya_udochka_c3
        idf.py set-target esp32c3
        idf.py build

    - name: Collect Binaries
      run: |
        mkdir VOSTOK_FIRMWARE
        mkdir VOSTOK_FIRMWARE/baza_s3
        mkdir VOSTOK_FIRMWARE/udochka_c3

        cp vostochnaya_baza_s3/build/bootloader/bootloader.bin VOSTOK_FIRMWARE/baza_s3/ || true
        cp vostochnaya_baza_s3/build/partition_table/partition-table.bin VOSTOK_FIRMWARE/baza_s3/ || true
        cp vostochnaya_baza_s3/build/vostochnaya_baza_s3.bin VOSTOK_FIRMWARE/baza_s3/ || true
        cp vostochnaya_baza_s3/build/storage.bin VOSTOK_FIRMWARE/baza_s3/ || true

        cp vostochnaya_udochka_c3/build/bootloader/bootloader.bin VOSTOK_FIRMWARE/udochka_c3/ || true
        cp vostochnaya_udochka_c3/build/partition_table/partition-table.bin VOSTOK_FIRMWARE/udochka_c3/ || true
        cp vostochnaya_udochka_c3/build/vostochnaya_udochka_c3.bin VOSTOK_FIRMWARE/udochka_c3/ || true

        apt-get update && apt-get install -y zip
        zip -r VOSTOK_FIRMWARE.zip VOSTOK_FIRMWARE

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VOSTOK_FIRMWARE
        path: VOSTOK_FIRMWARE.zip
